name: deploy-histdata

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Immutable application image tag (normally a Git SHA)
        required: true
      environment:
        type: choice
        options: [dev]
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN  }}
          aws-region: us-east-1
      - run: aws eks update-kubeconfig --name histdata-dev-eks --region us-east-1
      - name: Deploy immutable image
        run: |
          helm upgrade --install histdata charts/histdata \
            --namespace histdata --create-namespace \
            -f environments/${{ inputs.environment }}/values.yaml \
            --set-string image.tag=${{ inputs.image_tag }} \
            --atomic --timeout 10m
      - run: kubectl rollout status deployment/histdata-histdata -n histdata --timeout=5m

